window.__PUBLIC_STATE__ = {
  title: 'rradar station',
  path: ['articles', '254'],
  page: {
    title: 'Employment contracts ',
    description: '',
    slug: 'articles-single',
    id: 254,
    number: 1,
    sequence: null,
    actions: [],
    jurisdiction_name: 'England and Wales, Scotland',
    source: {
      id: 7,
      title: 'Internal',
      created_at: '2017-07-21T12:35:46.305Z',
      updated_at: '2017-07-21T12:35:46.305Z',
      description: null,
      address: null,
      logo_path: null,
      info_article_id: null,
      display: false,
    },
    category_ids: [1602],
    state: 'published',
  },
  config: {
    api: 'https://station.api.rradar.com',
    coronavirus: 'false',
    grace_api: null,
    grace_redirect_url_uid: 'b793eff5',
    redirect_url_uid: 'f7de904b',
    resourceManagerTemplateFolderUuid: 'adeec22c-9264-42e7-aece-01f3220f6326',
    resourceManagerAssetFolderUuid: 'a641188c-c13f-4167-98c3-c6c9e7cbbc64',
    resourceManagerSearchFolderUuid: '18b60faa-db35-4ff1-a418-32fd97d4ab07',
    joyrideReturnDays: '30',
    pusherId: '1a585a555f5eeb6d5ee5',
    lms_api: 'https://station.api.rradar.com',
    stationUrl: 'https://station.rradar.com/',
    helpArticleID: '5288',
    lock_time: 10,
  },
  user: {
    actor_uid: '114169:36',
    id: 114169,
    company_id: 36,
    first_name: 'Rapha',
    last_name: 'Weedon',
    email: 'rapha.weedon@rradar.com',
    company_name: 'rradar Limited',
    primary: true,
    expired: false,
    company_can_switch: true,
    company_sector_id: 8,
    locked: false,
    legal_access: false,
    created_at: '2025-01-29T15:05:24.527Z',
    updated_at: '2025-02-18T15:06:01.157Z',
    custom_landing_page: null,
    features: {
      ARTICLE_EDITING: {
        value: [''],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Article Editing',
        code_friendly_name: 'ARTICLE_EDITING',
        uid: '5793fb1d84b98dfab1dcdece4cca8c87',
      },
      ARTICLE_MANAGEMENT: {
        value: [''],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Article Management',
        code_friendly_name: 'ARTICLE_MANAGEMENT',
        uid: 'cf70ef58debdd93807300c82104af421',
      },
      TAXONOMY_MANAGEMENT: {
        value: [''],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Taxonomy Management',
        code_friendly_name: 'TAXONOMY_MANAGEMENT',
        uid: '00627804368594368fb3fbc21e619fe6',
      },
      SEARCH_REBUILD: {
        value: [''],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Search Rebuild',
        code_friendly_name: 'SEARCH_REBUILD',
        uid: 'a93903537be0c2e7a7d276c8cd2db3fe',
      },
      LIVECHAT_ACCESS: {
        value: ['', 'TRUE'],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Livechat access',
        code_friendly_name: 'LIVECHAT_ACCESS',
        uid: '1a04fbb1d9f8703cb8c299a7f96289cd',
      },
      CUSTOM_LANDING_PAGE: {
        value: [],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Custom Landing Page',
        code_friendly_name: 'CUSTOM_LANDING_PAGE',
        uid: '0cb260a37f573e2ff61366597f35819c',
      },
      HIDE_SITE_ELEMENTS: {
        value: [],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Hide Site Elements',
        code_friendly_name: 'HIDE_SITE_ELEMENTS',
        uid: '486cc1ccaca289f58226a2efcb241090',
      },
      BROKEN_LINKS_MANAGEMENT: {
        value: [],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Broken Links Management',
        code_friendly_name: 'BROKEN_LINKS_MANAGEMENT',
        uid: 'cf76a96e5cd962ee57a15f74500ed1cf',
      },
      STATIC_LANDING_CATEGORIES: {
        value: [],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Static Landing Categories',
        code_friendly_name: 'STATIC_LANDING_CATEGORIES',
        uid: '75efa9e21155becc67cce22efb11053f',
      },
      STATIC_ARTICLES: {
        value: [],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Static articles ',
        code_friendly_name: 'STATIC_ARTICLES',
        uid: '87095a9bcbe53da8381260a440dc083a',
      },
      CONTACT_DETAILS_OVERRIDE: {
        value: [],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Contact details override',
        code_friendly_name: 'CONTACT_DETAILS_OVERRIDE',
        uid: '88d7f748878021a3ae5b01d0aa359f64',
      },
    },
    features_by_key: {
      ARTICLE_EDITING: {
        value: [''],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Article Editing',
        code_friendly_name: 'ARTICLE_EDITING',
        uid: '5793fb1d84b98dfab1dcdece4cca8c87',
      },
      ARTICLE_MANAGEMENT: {
        value: [''],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Article Management',
        code_friendly_name: 'ARTICLE_MANAGEMENT',
        uid: 'cf70ef58debdd93807300c82104af421',
      },
      TAXONOMY_MANAGEMENT: {
        value: [''],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Taxonomy Management',
        code_friendly_name: 'TAXONOMY_MANAGEMENT',
        uid: '00627804368594368fb3fbc21e619fe6',
      },
      SEARCH_REBUILD: {
        value: [''],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Search Rebuild',
        code_friendly_name: 'SEARCH_REBUILD',
        uid: 'a93903537be0c2e7a7d276c8cd2db3fe',
      },
      LIVECHAT_ACCESS: {
        value: ['', 'TRUE'],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Livechat access',
        code_friendly_name: 'LIVECHAT_ACCESS',
        uid: '1a04fbb1d9f8703cb8c299a7f96289cd',
      },
      CUSTOM_LANDING_PAGE: {
        value: [],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Custom Landing Page',
        code_friendly_name: 'CUSTOM_LANDING_PAGE',
        uid: '0cb260a37f573e2ff61366597f35819c',
      },
      HIDE_SITE_ELEMENTS: {
        value: [],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Hide Site Elements',
        code_friendly_name: 'HIDE_SITE_ELEMENTS',
        uid: '486cc1ccaca289f58226a2efcb241090',
      },
      BROKEN_LINKS_MANAGEMENT: {
        value: [],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Broken Links Management',
        code_friendly_name: 'BROKEN_LINKS_MANAGEMENT',
        uid: 'cf76a96e5cd962ee57a15f74500ed1cf',
      },
      STATIC_LANDING_CATEGORIES: {
        value: [],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Static Landing Categories',
        code_friendly_name: 'STATIC_LANDING_CATEGORIES',
        uid: '75efa9e21155becc67cce22efb11053f',
      },
      STATIC_ARTICLES: {
        value: [],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Static articles ',
        code_friendly_name: 'STATIC_ARTICLES',
        uid: '87095a9bcbe53da8381260a440dc083a',
      },
      CONTACT_DETAILS_OVERRIDE: {
        value: [],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Contact details override',
        code_friendly_name: 'CONTACT_DETAILS_OVERRIDE',
        uid: '88d7f748878021a3ae5b01d0aa359f64',
      },
    },
    contents: {
      ELEARNING: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'eLearning',
        code_friendly_name: 'ELEARNING',
        uid: '72c29c1a7e18f373d7f5d2941b4d5dd7',
      },
      CYBER_ESSENTIALS: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'Cyber Essentials Accreditation',
        code_friendly_name: 'CYBER_ESSENTIALS',
        uid: '2307e1e83316328baf683ff5f6d8a21f',
      },
      WEBINARS: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'Webinars',
        code_friendly_name: 'WEBINARS',
        uid: '6ff8af2a988357798ba50ddec72b89c2',
      },
      MERGERS_ACQUISITIONS: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'M\u0026A',
        code_friendly_name: 'MERGERS_ACQUISITIONS',
        uid: 'f6fb9d46e5c7288d6150aea908c0c1ba',
      },
      BROKER_ACCESS: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'Broker Access',
        code_friendly_name: 'BROKER_ACCESS',
        uid: '972dfcd03138b0d838f2d981725f1efa',
      },
      SMALL_BUSINESS_CONTENT: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'Small Business Package',
        code_friendly_name: 'SMALL_BUSINESS_CONTENT',
        uid: '0afd17dcae61be1d72a3a135c0570bf5',
      },
      AXA_MLP_AGRI: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'AXA MLP Agriculture',
        code_friendly_name: 'AXA_MLP_AGRI',
        uid: '0ccd5cef3562991f889ec7a9ce2094d5',
      },
      CYBER_DEMO: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'AXA Cyber',
        code_friendly_name: 'CYBER_DEMO',
        uid: '8d3dfa7f0890a07f8832dd382eebe380',
      },
      FPB_GUIDES_ENDING: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'FPB Guides: Ending employment',
        code_friendly_name: 'FPB_GUIDES_ENDING',
        uid: 'eeb78b277c431efe833095cc4c7178fe',
      },
      AXA_HAULAGE: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'AXA Haulage',
        code_friendly_name: 'AXA_HAULAGE',
        uid: 'e1c39c1d4df3e9f6fcb5ad68c5c01e3e',
      },
      FPB_GUIDES_EQ_DIV: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'FPB Guides: Equality and diversity',
        code_friendly_name: 'FPB_GUIDES_EQ_DIV',
        uid: '66f774979960fe5d4648cc7c825c3b27',
      },
      FPB_GUIDES_DISC_GRIEV: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'FPB Guides: Managing disciplinary and grievance procedures',
        code_friendly_name: 'FPB_GUIDES_DISC_GRIEV',
        uid: '2b6d83df227eba20603b0752bc105346',
      },
      FPB_GUIDES_RECR_IND: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'FPB Guides: Recruitment and induction ',
        code_friendly_name: 'FPB_GUIDES_RECR_IND',
        uid: '71b754f7860aa8235b2d42072ceaa4e2',
      },
      AXA_PI_MISC: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'AXA PI Misc',
        code_friendly_name: 'AXA_PI_MISC',
        uid: 'b4aa328a6945f4689742b15e545742c5',
      },
      EMPLOYMENT_AND_HUMAN_RESOURCES: {
        value: null,
        amount: null,
        explicit: true,
        permission_type: 'content',
        name: 'Employment and Human Resources',
        code_friendly_name: 'EMPLOYMENT_AND_HUMAN_RESOURCES',
        uid: '7a08375141c4a900836d894ef40b1323',
      },
      DATA_MANAGEMENT_AND_DIGITAL_RISKS: {
        value: null,
        amount: null,
        explicit: true,
        permission_type: 'content',
        name: 'Data Management and Digital Risks',
        code_friendly_name: 'DATA_MANAGEMENT_AND_DIGITAL_RISKS',
        uid: '9cfdea48e0d3389eaf7fde7ceeb54b60',
      },
      MLSE___DATA_MANAGEMENT: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'MLSE - Data Management',
        code_friendly_name: 'MLSE___DATA_MANAGEMENT',
        uid: '87f2c9457c7a7b12999cb1be0612978d',
      },
      SOURCES_INFO: {
        value: null,
        amount: null,
        explicit: true,
        permission_type: 'content',
        name: 'Sources Info',
        code_friendly_name: 'SOURCES_INFO',
        uid: 'd4b4b09b008e5b113b9bb1b51172fa80',
      },
      MLSE___HR_AND_EMPLOYMENT: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'MLSE - HR and Employment',
        code_friendly_name: 'MLSE___HR_AND_EMPLOYMENT',
        uid: 'c5dd3bb2adac00d3b30e436a07031866',
      },
      MLSE___TAX: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'MLSE - Tax',
        code_friendly_name: 'MLSE___TAX',
        uid: 'b0f86c685e86a06a8ff28cdad31f9523',
      },
      TAX: {
        value: null,
        amount: null,
        explicit: true,
        permission_type: 'content',
        name: 'Tax',
        code_friendly_name: 'TAX',
        uid: '014b2ff3609ef8a3bc4c6a4be8a01cdf',
      },
      BUSINESS_CONTINUITY: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'Business Continuity',
        code_friendly_name: 'BUSINESS_CONTINUITY',
        uid: 'c56c715e8f0144b1ff34a9b86762b86d',
      },
      MLSE___HEALTH_AND_SAFETY: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'MLSE - Health and Safety',
        code_friendly_name: 'MLSE___HEALTH_AND_SAFETY',
        uid: '94ebb913b24125889d5d64981fc32f8c',
      },
      RISK_MANAGEMENT_GUIDANCE_NOTES: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'Risk Management Guidance Notes',
        code_friendly_name: 'RISK_MANAGEMENT_GUIDANCE_NOTES',
        uid: '915094faf1cfffbc961e951e690a3e58',
      },
      RISK_MANAGEMENT_CHECKLISTS: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'Risk Management Checklists',
        code_friendly_name: 'RISK_MANAGEMENT_CHECKLISTS',
        uid: '696330e99e0f57d39b8da7e3751c8077',
      },
      AXA_PI: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'AXA PI',
        code_friendly_name: 'AXA_PI',
        uid: '09c9d9b6a5c42927f0b487f1bc6acd3d',
      },
      WTW_GUIDANCE_NOTES: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'WTW Guidance Notes',
        code_friendly_name: 'WTW_GUIDANCE_NOTES',
        uid: '0e5b20f25ac77854f91f6168707c845b',
      },
      WTW_DOWNLOADABLE_CHECKLISTS: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'WTW Downloadable Checklists',
        code_friendly_name: 'WTW_DOWNLOADABLE_CHECKLISTS',
        uid: '27380259919ee630256ecae9f53abcea',
      },
      CIVIL_DISPUTES: {
        value: null,
        amount: null,
        explicit: true,
        permission_type: 'content',
        name: 'Civil Disputes',
        code_friendly_name: 'CIVIL_DISPUTES',
        uid: '836956a85a4f6ea68cda7b2c09e3eedd',
      },
      PROPERTY_MANAGEMENT_AND_LICENSED_PREMISES: {
        value: null,
        amount: null,
        explicit: true,
        permission_type: 'content',
        name: 'Property Management and Licensed Premises',
        code_friendly_name: 'PROPERTY_MANAGEMENT_AND_LICENSED_PREMISES',
        uid: '00466120d9c2b7e83b8b66b7bed494f6',
      },
      CRIMINAL_AND_REGULATORY: {
        value: null,
        amount: null,
        explicit: true,
        permission_type: 'content',
        name: 'Criminal and Regulatory',
        code_friendly_name: 'CRIMINAL_AND_REGULATORY',
        uid: '7fbbe06f03dffbee70f6f3d6d2a1688b',
      },
      COMPANY_AND_COMMERCIAL: {
        value: null,
        amount: null,
        explicit: true,
        permission_type: 'content',
        name: 'Company and Commercial',
        code_friendly_name: 'COMPANY_AND_COMMERCIAL',
        uid: '826f686a281bcc1fa898678b2962c3ed',
      },
      LEGAL_OVERVIEW: {
        value: null,
        amount: null,
        explicit: true,
        permission_type: 'content',
        name: 'Legal Overview',
        code_friendly_name: 'LEGAL_OVERVIEW',
        uid: '8f17fca4f1835c5bbe31f27cc23f7a74',
      },
      LEGAL_COMPLIANCE_AND_PROCEDURES: {
        value: null,
        amount: null,
        explicit: true,
        permission_type: 'content',
        name: 'Legal Compliance and Procedures',
        code_friendly_name: 'LEGAL_COMPLIANCE_AND_PROCEDURES',
        uid: '5f5be830303524f66a195887685e7f79',
      },
      HEALTH_SAFETY_AND_ENVIRONMENT: {
        value: null,
        amount: null,
        explicit: true,
        permission_type: 'content',
        name: 'Health, Safety and Environment',
        code_friendly_name: 'HEALTH_SAFETY_AND_ENVIRONMENT',
        uid: '891407bb0e3d60a98a3553f7f301deff',
      },
      SECTOR_SPECIFIC: {
        value: null,
        amount: null,
        explicit: true,
        permission_type: 'content',
        name: 'Sector specific',
        code_friendly_name: 'SECTOR_SPECIFIC',
        uid: '63574cb380726c77f86a0a870e461b1d',
      },
      DRIVING_RISK: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'Driving Risk',
        code_friendly_name: 'DRIVING_RISK',
        uid: '7e31452cd0d49c120f1ad4ea2fc3677f',
      },
      COVID_19: {
        value: null,
        amount: null,
        explicit: true,
        permission_type: 'content',
        name: 'Covid-19',
        code_friendly_name: 'COVID_19',
        uid: 'f5e529b09a40e55adb5f39ae668c0768',
      },
      COVID_19_EXCLUSIVE: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'Covid-19 Exclusive',
        code_friendly_name: 'COVID_19_EXCLUSIVE',
        uid: '9eccb2d528005a38f70d8ec17a6dce85',
      },
      EMPLOYER_PROTECT: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'Employer Protect',
        code_friendly_name: 'EMPLOYER_PROTECT',
        uid: 'bd9c807645185400aef9657600248d45',
      },
      FPB_GUIDES_ABS_PAY: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'FPB Guides: Absence and pay',
        code_friendly_name: 'FPB_GUIDES_ABS_PAY',
        uid: '4835d1d336eceb7421794cb56bf6bf6a',
      },
      CYBER_BROKER_SAMPLE_STATION_CONTENT: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'Cyber broker sample station content',
        code_friendly_name: 'CYBER_BROKER_SAMPLE_STATION_CONTENT',
        uid: '8cd746944e0c1b5f334fbe28602f1af8',
      },
      MNPMIWSS: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'MIND PWSS',
        code_friendly_name: 'MNPMIWSS',
        uid: '0248feaab06382f23a55f6ebbb8d85b0',
      },
      FPB_GUIDES_ACCIDENTS_AND_EMERGENCIES: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'FPB Guides: Accidents and Emergencies',
        code_friendly_name: 'FPB_GUIDES_ACCIDENTS_AND_EMERGENCIES',
        uid: '0754e0e776af223ee8a61eed2c5fa472',
      },
      FPB_GUIDES_RISK_ASSESSMENTS_AND_MANAGEMENT: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'FPB Guides: Risk Assessments and Management',
        code_friendly_name: 'FPB_GUIDES_RISK_ASSESSMENTS_AND_MANAGEMENT',
        uid: 'c0e52d5e630f0b6526a537d97a3c0ad5',
      },
      FPB_GUIDES_H_AND_S_RESPONSIBILITIES: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'FPB Guides: H and S Responsibilities',
        code_friendly_name: 'FPB_GUIDES_H_AND_S_RESPONSIBILITIES',
        uid: 'fbf56d69686e7db8113c5e0b0e074dcb',
      },
      FPB_GUIDES_H_AND_S_POLICIES_AND_DOCUMENTS: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'FPB Guides: H and S Policies and Documents',
        code_friendly_name: 'FPB_GUIDES_H_AND_S_POLICIES_AND_DOCUMENTS',
        uid: '02bda1ffd8c99f896fb173d816511076',
      },
    },
    user: {
      updated_at: '2024-06-24T15:36:16.669Z',
      joyride_home: false,
      joyride_categories: false,
      joyride_articles: true,
      accessed_at: '2025-02-26T00:25:20.087Z',
      joyride_return: false,
    },
    switch_company_url:
      'https://accounts.api.rradar.com/login/companyselect?client_id=162e8eb9-6165-47a5-8edb-61c8c6a99e64',
    avatar_url:
      'https://www.gravatar.com/avatar/744a859024066dc447b3510ca1fff96b?d=https://my.rradar.com/assets/img/default-profile.png',
    applications: [
      {
        id: 3,
        name: 'Grace',
        description:
          'The intelligent legal assistant for quick, reliable legal support on-the-go from your smart device.',
        display_name: 'Grace',
        application_url: 'https://grace.rradar.com',
        code_friendly_name: 'GRACE',
        app_store: {
          ios: {
            url: 'https://apps.apple.com/gb/app/rradargrace/id1198208995',
          },
          android: {
            id: 'com.radar.grace',
            url: 'https://play.google.com/store/apps/details?id=com.radar.grace\u0026hl=en_GB',
          },
        },
        marketing_url: null,
        light_logo_url:
          'https://rradar-accounts.imgix.net/uploads/ba71f813-4d65-4345-95b7-0e78c08f3b87.svg?ixlib=rb-3.1.1',
        dark_logo_url:
          'https://rradar-accounts.imgix.net/uploads/5b19d7f2-c50d-4223-8288-90431b3af328.svg?ixlib=rb-3.1.1',
        screenshots: [
          {
            id: 53,
            uuid: '15f72002-0c9a-4df2-a4b4-9c804f28af2a',
            file_type: 'jpeg',
            created_at: '2020-03-25T10:24:18.882Z',
            updated_at: '2020-03-25T10:24:18.882Z',
            assigned: true,
            position: 1,
            caption: null,
            url: 'https://rradar-accounts.imgix.net/uploads/15f72002-0c9a-4df2-a4b4-9c804f28af2a.jpeg?ixlib=rb-3.1.1',
          },
        ],
        visuals: [
          {
            id: 53,
            uuid: '15f72002-0c9a-4df2-a4b4-9c804f28af2a',
            file_type: 'jpeg',
            created_at: '2020-03-25T10:24:18.882Z',
            updated_at: '2020-03-25T10:24:18.882Z',
            assigned: true,
            position: 1,
            caption: null,
            url: 'https://rradar-accounts.imgix.net/uploads/15f72002-0c9a-4df2-a4b4-9c804f28af2a.jpeg?ixlib=rb-3.1.1',
          },
        ],
      },
      {
        id: 4,
        name: 'Station',
        description:
          'The online knowledge library packed with legal and risk management articles, guides and templates.',
        display_name: 'Station',
        application_url: 'https://station.rradar.com',
        code_friendly_name: 'STATION',
        app_store: {},
        marketing_url: null,
        light_logo_url:
          'https://rradar-accounts.imgix.net/uploads/efecf2bd-6501-4620-955e-68b8562856d2.svg?ixlib=rb-3.1.1',
        dark_logo_url:
          'https://rradar-accounts.imgix.net/uploads/f99b5100-76af-48df-ba8e-41dc8c1c9c8d.svg?ixlib=rb-3.1.1',
        screenshots: [
          {
            id: 54,
            uuid: 'b9d399e7-8412-4096-8dc7-ad5978f12a07',
            file_type: 'jpeg',
            created_at: '2020-03-25T10:25:11.875Z',
            updated_at: '2020-03-25T10:25:11.875Z',
            assigned: true,
            position: 1,
            caption: null,
            url: 'https://rradar-accounts.imgix.net/uploads/b9d399e7-8412-4096-8dc7-ad5978f12a07.jpeg?ixlib=rb-3.1.1',
          },
        ],
        visuals: [
          {
            id: 54,
            uuid: 'b9d399e7-8412-4096-8dc7-ad5978f12a07',
            file_type: 'jpeg',
            created_at: '2020-03-25T10:25:11.875Z',
            updated_at: '2020-03-25T10:25:11.875Z',
            assigned: true,
            position: 1,
            caption: null,
            url: 'https://rradar-accounts.imgix.net/uploads/b9d399e7-8412-4096-8dc7-ad5978f12a07.jpeg?ixlib=rb-3.1.1',
          },
        ],
      },
      {
        id: 5,
        name: 'Report',
        description:
          'The incident reporting tool to document, manage and respond to risks, as and when they happen.',
        display_name: 'Report',
        application_url: 'https://report.rradar.com',
        code_friendly_name: 'REPORT',
        app_store: {
          ios: {
            url: 'https://apps.apple.com/gb/app/rradarreport/id1269011148',
          },
          android: {
            url: 'https://play.google.com/store/apps/details?id=com.rradar.incidentreporting',
          },
        },
        marketing_url: null,
        light_logo_url:
          'https://rradar-accounts.imgix.net/uploads/e6ba013a-e8bf-4f1b-820a-e3057f5cfd3f.svg?ixlib=rb-3.1.1',
        dark_logo_url:
          'https://rradar-accounts.imgix.net/uploads/e1661ceb-ae34-4abb-9816-bfb217780f58.svg?ixlib=rb-3.1.1',
        screenshots: [
          {
            id: 55,
            uuid: '7aa2e0e8-e9c8-4004-bced-a6295c3124cf',
            file_type: 'jpeg',
            created_at: '2020-03-25T10:25:24.709Z',
            updated_at: '2020-03-25T10:25:24.709Z',
            assigned: true,
            position: 1,
            caption: '',
            url: 'https://rradar-accounts.imgix.net/uploads/7aa2e0e8-e9c8-4004-bced-a6295c3124cf.jpeg?ixlib=rb-3.1.1',
          },
        ],
        visuals: [
          {
            id: 55,
            uuid: '7aa2e0e8-e9c8-4004-bced-a6295c3124cf',
            file_type: 'jpeg',
            created_at: '2020-03-25T10:25:24.709Z',
            updated_at: '2020-03-25T10:25:24.709Z',
            assigned: true,
            position: 1,
            caption: '',
            url: 'https://rradar-accounts.imgix.net/uploads/7aa2e0e8-e9c8-4004-bced-a6295c3124cf.jpeg?ixlib=rb-3.1.1',
          },
        ],
      },
      {
        id: 14,
        name: 'Whistlebox',
        description:
          'The whistleblowing solution that creates a safe space for employees to raise their concerns.',
        display_name: 'Whistlebox',
        application_url: 'https://whistlebox.rradar.com',
        code_friendly_name: 'WHISTLEBOX',
        app_store: {},
        marketing_url: null,
        light_logo_url:
          'https://rradar-accounts.imgix.net/uploads/5aac3af3-b30b-4d75-b924-6f8ce56c0ecb.svg?ixlib=rb-3.1.1',
        dark_logo_url:
          'https://rradar-accounts.imgix.net/uploads/4928f2cb-b0fe-48bf-bd55-8d9bc3cb9bc7.svg?ixlib=rb-3.1.1',
        screenshots: [],
        visuals: [],
      },
      {
        id: 18,
        name: 'Recover',
        description:
          'The powerful and effective online debt recovery solution, helping you save time and money.',
        display_name: 'Recover',
        application_url: 'https://recover.rradar.com',
        code_friendly_name: 'RECOVER',
        app_store: {},
        marketing_url: null,
        light_logo_url:
          'https://rradar-accounts.imgix.net/uploads/f0f8535f-abd2-4d4d-be01-99dba3e2c165.svg?ixlib=rb-3.1.1',
        dark_logo_url:
          'https://rradar-accounts.imgix.net/uploads/b0ab009b-d078-42f8-8456-e0be5afa6371.svg?ixlib=rb-3.1.1',
        screenshots: [
          {
            id: 60,
            uuid: '11803ec8-8c90-45d7-b555-550c160c4954',
            file_type: 'jpg',
            created_at: '2020-03-26T11:34:07.057Z',
            updated_at: '2020-03-26T11:34:07.057Z',
            assigned: true,
            position: 3,
            caption: null,
            url: 'https://rradar-accounts.imgix.net/uploads/11803ec8-8c90-45d7-b555-550c160c4954.jpg?ixlib=rb-3.1.1',
          },
        ],
        visuals: [
          {
            id: 60,
            uuid: '11803ec8-8c90-45d7-b555-550c160c4954',
            file_type: 'jpg',
            created_at: '2020-03-26T11:34:07.057Z',
            updated_at: '2020-03-26T11:34:07.057Z',
            assigned: true,
            position: 3,
            caption: null,
            url: 'https://rradar-accounts.imgix.net/uploads/11803ec8-8c90-45d7-b555-550c160c4954.jpg?ixlib=rb-3.1.1',
          },
        ],
      },
      {
        id: 27,
        name: 'Risk UI',
        description:
          'Our business risk analysis tool identifies the risks to your business and suggests how to minimise problems before they happen.',
        display_name: 'RISK',
        application_url: 'https://risk.rradar.com',
        code_friendly_name: 'RISK_UI',
        app_store: {},
        marketing_url: null,
        light_logo_url:
          'https://rradar-accounts.imgix.net/uploads/cd73eb65-42f1-4bb2-866c-6f63960b9348.svg?ixlib=rb-3.1.1',
        dark_logo_url:
          'https://rradar-accounts.imgix.net/uploads/7b472670-a975-4cad-a4e6-773422c4902b.svg?ixlib=rb-3.1.1',
        screenshots: [],
        visuals: [],
      },
    ],
    mlse_policy: false,
    all_content: false,
    static_categories: null,
    hide_site_elements: [],
    contact_details_override: null,
  },
  permissions: [
    'ARTICLE_EDITING',
    'ARTICLE_MANAGEMENT',
    'TAXONOMY_MANAGEMENT',
    'SEARCH_REBUILD',
    'LIVECHAT_ACCESS',
    'CUSTOM_LANDING_PAGE',
    'HIDE_SITE_ELEMENTS',
    'BROKEN_LINKS_MANAGEMENT',
    'STATIC_LANDING_CATEGORIES',
    'STATIC_ARTICLES',
    'CONTACT_DETAILS_OVERRIDE',
  ],
  sentry: {
    dsn: 'https://16f72b0f325040a18d0b301e23193e35@o162270.ingest.sentry.io/1242782',
    key: '16f72b0f325040a18d0b301e23193e35',
    project: '1242782',
    environment: 'production',
  },
};
