window.__PUBLIC_STATE__ = {
  title: 'Station Tool',
  user: {
    actor_uid: '15316:36',
    id: 15316,
    company_id: 36,
    first_name: 'Rapha',
    last_name: 'Weedon',
    email: 'rapha.weedon@rradar.com',
    company_name: 'rradar',
    primary: true,
    expired: false,
    company_can_switch: true,
    company_sector_id: 8,
    locked: false,
    legal_access: true,
    created_at: '2025-01-22T11:04:24.071Z',
    updated_at: '2025-02-18T17:37:19.787Z',
    custom_landing_page: 'cyber-essentials',
    features: {
      STATIC_LANDING_CATEGORIES: {
        value: ['1611'],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Static Landing Categories ',
        code_friendly_name: 'STATIC_LANDING_CATEGORIES',
        uid: '51c5d1431114c0f23090701973b7b4d6',
      },
      CUSTOM_LANDING_PAGE: {
        value: ['cyber-essentials', 'other', 'other'],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Custom Landing Page',
        code_friendly_name: 'CUSTOM_LANDING_PAGE',
        uid: '0cb260a37f573e2ff61366597f35819c',
      },
      SEARCH_REBUILD: {
        value: ['TOOLS_SEARCH_REBUILD'],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Search Rebuild',
        code_friendly_name: 'SEARCH_REBUILD',
        uid: 'a93903537be0c2e7a7d276c8cd2db3fe',
      },
      TAXONOMY_MANAGEMENT: {
        value: [
          'COUNTRY_CREATE, COUNTRY_UPDATE, COUNTRY_DELETE, CATEGORY_CREATE, CATEGORY_UPDATE, CATEGORY_DELETE, SECTOR_CREATE, SECTOR_UPDATE, SECTOR_DELETE, TAG_UPDATE, TAG_DELETE, STAGE_CREATE, STAGE_UPDATE, STAGE_DELETE',
        ],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Taxonomy Management',
        code_friendly_name: 'TAXONOMY_MANAGEMENT',
        uid: '00627804368594368fb3fbc21e619fe6',
      },
      ARTICLE_MANAGEMENT: {
        value: ['ARTICLE_DELETE, ARTICLE_REVISION_REVERT, ARTICLE_PUBLISHING'],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Article Management',
        code_friendly_name: 'ARTICLE_MANAGEMENT',
        uid: 'cf70ef58debdd93807300c82104af421',
      },
      ARTICLE_EDITING: {
        value: [
          'ARTICLE_MANAGER, ARTICLE_CREATE, ARTICLE_UPDATE, ARTICLE_CATEGORY_MANAGER, ARTICLE_RELATED_MANAGER, ARTICLE_SECTOR_MANAGER, ARTICLE_TAG_MANAGER, ARTICLE_TEMPLATE_MANAGER, ARTICLE_REVISION_LIST, STATE_READ',
        ],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Article Editing',
        code_friendly_name: 'ARTICLE_EDITING',
        uid: '5793fb1d84b98dfab1dcdece4cca8c87',
      },
      ALL_CONTENT: {
        value: [],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'All Content',
        code_friendly_name: 'ALL_CONTENT',
        uid: '0581ba11b73d3d125c5389ec6c48e8de',
      },
      CAN_DOWNLOAD_TEMPLATE: {
        value: ['', ''],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Can Download Template',
        code_friendly_name: 'CAN_DOWNLOAD_TEMPLATE',
        uid: '15affc6a2722f4fc7cfe186d63cc7aa2',
      },
      CAN_VIEW_TEMPLATE: {
        value: ['', ''],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Can View Template',
        code_friendly_name: 'CAN_VIEW_TEMPLATE',
        uid: '37505666e57dc8e701a1137db60cb123',
      },
      LIVE_CHAT_ACCESS: {
        value: ['', 'true'],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Live Chat Access',
        code_friendly_name: 'LIVE_CHAT_ACCESS',
        uid: '9ecf22eaa93e081a5f710496a9631d81',
      },
      BROKEN_LINKS_MANAGEMENT: {
        value: [''],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Broken Links Management',
        code_friendly_name: 'BROKEN_LINKS_MANAGEMENT',
        uid: 'cf76a96e5cd962ee57a15f74500ed1cf',
      },
    },
    features_by_key: {
      STATIC_LANDING_CATEGORIES: {
        value: ['1611'],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Static Landing Categories ',
        code_friendly_name: 'STATIC_LANDING_CATEGORIES',
        uid: '51c5d1431114c0f23090701973b7b4d6',
      },
      CUSTOM_LANDING_PAGE: {
        value: ['cyber-essentials', 'other', 'other'],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Custom Landing Page',
        code_friendly_name: 'CUSTOM_LANDING_PAGE',
        uid: '0cb260a37f573e2ff61366597f35819c',
      },
      SEARCH_REBUILD: {
        value: ['TOOLS_SEARCH_REBUILD'],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Search Rebuild',
        code_friendly_name: 'SEARCH_REBUILD',
        uid: 'a93903537be0c2e7a7d276c8cd2db3fe',
      },
      TAXONOMY_MANAGEMENT: {
        value: [
          'COUNTRY_CREATE, COUNTRY_UPDATE, COUNTRY_DELETE, CATEGORY_CREATE, CATEGORY_UPDATE, CATEGORY_DELETE, SECTOR_CREATE, SECTOR_UPDATE, SECTOR_DELETE, TAG_UPDATE, TAG_DELETE, STAGE_CREATE, STAGE_UPDATE, STAGE_DELETE',
        ],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Taxonomy Management',
        code_friendly_name: 'TAXONOMY_MANAGEMENT',
        uid: '00627804368594368fb3fbc21e619fe6',
      },
      ARTICLE_MANAGEMENT: {
        value: ['ARTICLE_DELETE, ARTICLE_REVISION_REVERT, ARTICLE_PUBLISHING'],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Article Management',
        code_friendly_name: 'ARTICLE_MANAGEMENT',
        uid: 'cf70ef58debdd93807300c82104af421',
      },
      ARTICLE_EDITING: {
        value: [
          'ARTICLE_MANAGER, ARTICLE_CREATE, ARTICLE_UPDATE, ARTICLE_CATEGORY_MANAGER, ARTICLE_RELATED_MANAGER, ARTICLE_SECTOR_MANAGER, ARTICLE_TAG_MANAGER, ARTICLE_TEMPLATE_MANAGER, ARTICLE_REVISION_LIST, STATE_READ',
        ],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Article Editing',
        code_friendly_name: 'ARTICLE_EDITING',
        uid: '5793fb1d84b98dfab1dcdece4cca8c87',
      },
      ALL_CONTENT: {
        value: [],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'All Content',
        code_friendly_name: 'ALL_CONTENT',
        uid: '0581ba11b73d3d125c5389ec6c48e8de',
      },
      CAN_DOWNLOAD_TEMPLATE: {
        value: ['', ''],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Can Download Template',
        code_friendly_name: 'CAN_DOWNLOAD_TEMPLATE',
        uid: '15affc6a2722f4fc7cfe186d63cc7aa2',
      },
      CAN_VIEW_TEMPLATE: {
        value: ['', ''],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Can View Template',
        code_friendly_name: 'CAN_VIEW_TEMPLATE',
        uid: '37505666e57dc8e701a1137db60cb123',
      },
      LIVE_CHAT_ACCESS: {
        value: ['', 'true'],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Live Chat Access',
        code_friendly_name: 'LIVE_CHAT_ACCESS',
        uid: '9ecf22eaa93e081a5f710496a9631d81',
      },
      BROKEN_LINKS_MANAGEMENT: {
        value: [''],
        amount: [],
        explicit: false,
        permission_type: 'feature',
        name: 'Broken Links Management',
        code_friendly_name: 'BROKEN_LINKS_MANAGEMENT',
        uid: 'cf76a96e5cd962ee57a15f74500ed1cf',
      },
    },
    contents: {
      DATA_MANAGEMENT_AND_DIGITAL_RISKS: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'Data Management and Digital Risks',
        code_friendly_name: 'DATA_MANAGEMENT_AND_DIGITAL_RISKS',
        uid: '9cfdea48e0d3389eaf7fde7ceeb54b60',
      },
      COVID_19_ADVICE: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'Covid-19 Advice',
        code_friendly_name: 'COVID_19_ADVICE',
        uid: '93282fa17d173822b75dc4ab516b6898',
      },
      STATION_DEVELOPMENT_CONTENT: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'Station Development Content',
        code_friendly_name: 'STATION_DEVELOPMENT_CONTENT',
        uid: '0ff47d7625215deb505666983f6005eb',
      },
      COMPANY_AND_COMMERCIAL: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'Company and Commercial',
        code_friendly_name: 'COMPANY_AND_COMMERCIAL',
        uid: '826f686a281bcc1fa898678b2962c3ed',
      },
      CIVIL_DISPUTES: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'Civil Disputes',
        code_friendly_name: 'CIVIL_DISPUTES',
        uid: '836956a85a4f6ea68cda7b2c09e3eedd',
      },
      LEGAL_COMPLIANCE_AND_PROCEDURES: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'Legal Compliance and Procedures',
        code_friendly_name: 'LEGAL_COMPLIANCE_AND_PROCEDURES',
        uid: '5f5be830303524f66a195887685e7f79',
      },
      LEGAL_OVERVIEW: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'Legal Overview',
        code_friendly_name: 'LEGAL_OVERVIEW',
        uid: '8f17fca4f1835c5bbe31f27cc23f7a74',
      },
      SECTOR_SPECIFIC: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'Sector specific',
        code_friendly_name: 'SECTOR_SPECIFIC',
        uid: '63574cb380726c77f86a0a870e461b1d',
      },
      A_TEST_EMPTY_CATEGORY: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'A test empty category',
        code_friendly_name: 'A_TEST_EMPTY_CATEGORY',
        uid: '66513eeb73d68030c0dbebb96251c334',
      },
      CRIMINAL_AND_REGULATORY: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'Criminal and Regulatory',
        code_friendly_name: 'CRIMINAL_AND_REGULATORY',
        uid: '7fbbe06f03dffbee70f6f3d6d2a1688b',
      },
      PROPERTY_MANAGEMENT_AND_LICENSED_PREMISES: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'Property Management and Licensed Premises',
        code_friendly_name: 'PROPERTY_MANAGEMENT_AND_LICENSED_PREMISES',
        uid: '00466120d9c2b7e83b8b66b7bed494f6',
      },
      HEALTH_SAFETY_AND_ENVIRONMENT: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'Health, Safety and Environment',
        code_friendly_name: 'HEALTH_SAFETY_AND_ENVIRONMENT',
        uid: '891407bb0e3d60a98a3553f7f301deff',
      },
      WEBINARS: {
        value: null,
        amount: null,
        explicit: false,
        permission_type: 'content',
        name: 'Webinars',
        code_friendly_name: 'WEBINARS',
        uid: '6ff8af2a988357798ba50ddec72b89c2',
      },
    },
    user: {
      updated_at: '2024-09-03T15:47:05.892Z',
      joyride_home: false,
      joyride_categories: false,
      joyride_articles: true,
      accessed_at: '2025-02-26T01:54:13.655Z',
      joyride_return: false,
    },
    switch_company_url:
      'https://accounts.api.2ra.co.uk/login/companyselect?client_id=29c1bcdb-dbd0-425a-9d2a-35c6f6c43902',
    avatar_url:
      'https://www.gravatar.com/avatar/744a859024066dc447b3510ca1fff96b?d=https://my.rradar.com/assets/img/default-profile.png',
    applications: [
      {
        id: 3,
        name: 'Grace',
        description:
          'Grace Development Server Application. This provides access to the grace application on the rradar development server.',
        display_name: 'Grace',
        application_url: null,
        code_friendly_name: 'GRACE',
        app_store: {
          ios: {
            url: 'https://apps.apple.com/gb/app/rradargrace/id1198208995',
          },
          android: {
            id: 'com.radar.grace',
            url: 'https://play.google.com/store/apps/details?id=com.radar.grace&hl=en_GB',
          },
        },
        marketing_url: 'https://www.rradar.com/rradargrace',
        light_logo_url:
          'https://rradar-accounts.imgix.net/uploads/f2b9984e-a5fb-4373-ae9e-d04540a94024.svg?ixlib=rb-3.1.1',
        dark_logo_url:
          'https://rradar-accounts.imgix.net/uploads/38b2c1ce-b10f-4850-9830-a090843f4f22.svg?ixlib=rb-3.1.1',
        screenshots: [
          {
            id: 53,
            uuid: '77d259dc-6a5e-438d-84ed-bb4537f45166',
            file_type: 'jpeg',
            created_at: '2020-03-20T11:48:36.507Z',
            updated_at: '2020-03-20T11:48:36.507Z',
            assigned: true,
            position: 1,
            caption: null,
            url: 'https://rradar-accounts.imgix.net/uploads/77d259dc-6a5e-438d-84ed-bb4537f45166.jpeg?ixlib=rb-3.1.1',
          },
          {
            id: 66,
            uuid: '3a6bee87-3e4b-4277-bf8a-9a9d9e983fb3',
            file_type: 'jpg',
            created_at: '2020-07-17T12:36:35.919Z',
            updated_at: '2020-07-17T12:36:35.919Z',
            assigned: true,
            position: 2,
            caption: null,
            url: 'https://rradar-accounts.imgix.net/uploads/3a6bee87-3e4b-4277-bf8a-9a9d9e983fb3.jpg?ixlib=rb-3.1.1',
          },
        ],
        visuals: [
          {
            id: 53,
            uuid: '77d259dc-6a5e-438d-84ed-bb4537f45166',
            file_type: 'jpeg',
            created_at: '2020-03-20T11:48:36.507Z',
            updated_at: '2020-03-20T11:48:36.507Z',
            assigned: true,
            position: 1,
            caption: null,
            url: 'https://rradar-accounts.imgix.net/uploads/77d259dc-6a5e-438d-84ed-bb4537f45166.jpeg?ixlib=rb-3.1.1',
          },
          {
            id: 66,
            uuid: '3a6bee87-3e4b-4277-bf8a-9a9d9e983fb3',
            file_type: 'jpg',
            created_at: '2020-07-17T12:36:35.919Z',
            updated_at: '2020-07-17T12:36:35.919Z',
            assigned: true,
            position: 2,
            caption: null,
            url: 'https://rradar-accounts.imgix.net/uploads/3a6bee87-3e4b-4277-bf8a-9a9d9e983fb3.jpg?ixlib=rb-3.1.1',
          },
        ],
      },
      {
        id: 6,
        name: 'Report',
        description:
          'Report Development Application. This provides access to the report application on the rradar development server.',
        display_name: 'Report',
        application_url: 'https://report.ui.2ra.co.uk',
        code_friendly_name: 'REPORT_DEVELOPMENT',
        app_store: {
          ios: {
            url: 'https://apps.apple.com/gb/app/rradarreport/id1269011148',
          },
          android: {
            url: 'https://play.google.com/store/apps/details?id=com.rradar.incidentreporting',
          },
        },
        marketing_url: null,
        light_logo_url:
          'https://rradar-accounts.imgix.net/uploads/85184f77-fb5e-466b-ba93-56e76e9f176c.svg?ixlib=rb-3.1.1',
        dark_logo_url:
          'https://rradar-accounts.imgix.net/uploads/eb54a9bc-2691-46ac-b2e9-70a84974cafa.svg?ixlib=rb-3.1.1',
        screenshots: [
          {
            id: 51,
            uuid: 'ea55583f-00c4-4da6-ac98-04fdc66c4eb3',
            file_type: 'jpeg',
            created_at: '2020-03-20T11:45:03.920Z',
            updated_at: '2020-03-20T11:45:03.920Z',
            assigned: true,
            position: 1,
            caption: null,
            url: 'https://rradar-accounts.imgix.net/uploads/ea55583f-00c4-4da6-ac98-04fdc66c4eb3.jpeg?ixlib=rb-3.1.1',
          },
        ],
        visuals: [
          {
            id: 51,
            uuid: 'ea55583f-00c4-4da6-ac98-04fdc66c4eb3',
            file_type: 'jpeg',
            created_at: '2020-03-20T11:45:03.920Z',
            updated_at: '2020-03-20T11:45:03.920Z',
            assigned: true,
            position: 1,
            caption: null,
            url: 'https://rradar-accounts.imgix.net/uploads/ea55583f-00c4-4da6-ac98-04fdc66c4eb3.jpeg?ixlib=rb-3.1.1',
          },
        ],
      },
      {
        id: 8,
        name: 'Station',
        description:
          'Station Development Application. This provides access to the station application on the rradar development server.',
        display_name: 'Station',
        application_url: 'https://station.ui.2ra.co.uk',
        code_friendly_name: 'STATION',
        app_store: {},
        marketing_url: null,
        light_logo_url:
          'https://rradar-accounts.imgix.net/uploads/8dc533c7-ad61-4e82-aa75-3f47b2b46e05.svg?ixlib=rb-3.1.1',
        dark_logo_url:
          'https://rradar-accounts.imgix.net/uploads/cea60d5f-a15e-411b-9791-24745e233d77.svg?ixlib=rb-3.1.1',
        screenshots: [
          {
            id: 52,
            uuid: '3d258b20-613a-4fa0-9383-23a20df6be77',
            file_type: 'jpeg',
            created_at: '2020-03-20T11:47:42.176Z',
            updated_at: '2020-03-20T11:47:42.176Z',
            assigned: true,
            position: 1,
            caption: null,
            url: 'https://rradar-accounts.imgix.net/uploads/3d258b20-613a-4fa0-9383-23a20df6be77.jpeg?ixlib=rb-3.1.1',
          },
        ],
        visuals: [
          {
            id: 52,
            uuid: '3d258b20-613a-4fa0-9383-23a20df6be77',
            file_type: 'jpeg',
            created_at: '2020-03-20T11:47:42.176Z',
            updated_at: '2020-03-20T11:47:42.176Z',
            assigned: true,
            position: 1,
            caption: null,
            url: 'https://rradar-accounts.imgix.net/uploads/3d258b20-613a-4fa0-9383-23a20df6be77.jpeg?ixlib=rb-3.1.1',
          },
        ],
      },
      {
        id: 13,
        name: 'Whistlebox',
        description:
          'Whistlebox Development Application. This provides access to the whistlebox application on the rradar development server.',
        display_name: 'Whistlebox',
        application_url: 'http://whistlebox.rradar.com',
        code_friendly_name: 'WHISTLEBOX',
        app_store: {},
        marketing_url: null,
        light_logo_url:
          'https://rradar-accounts.imgix.net/uploads/341a4fed-afd9-4e0a-a379-97c16d5eb671.svg?ixlib=rb-3.1.1',
        dark_logo_url:
          'https://rradar-accounts.imgix.net/uploads/bbf88584-b71b-4f1d-b249-f6ceba9ce447.svg?ixlib=rb-3.1.1',
        screenshots: [],
        visuals: [],
      },
      {
        id: 18,
        name: 'Recover',
        description:
          'Recover Development Application. This provides access to the recover application on the rradar development server.',
        display_name: 'rradarrecover',
        application_url: 'https://recover.ui.2ra.co.uk/dashboard',
        code_friendly_name: 'RECOVER_DEVELOPMENT',
        app_store: {},
        marketing_url: null,
        light_logo_url:
          'https://rradar-accounts.imgix.net/uploads/ef985da3-5b61-4504-a596-99a23798b278.svg?ixlib=rb-3.1.1',
        dark_logo_url:
          'https://rradar-accounts.imgix.net/uploads/dd4c849f-da2c-4004-91e6-c3df940a0916.svg?ixlib=rb-3.1.1',
        screenshots: [
          {
            id: 59,
            uuid: '32acb501-d2ce-45c5-b2ad-7d30cad6556b',
            file_type: 'jpeg',
            created_at: '2020-03-20T11:57:16.743Z',
            updated_at: '2020-03-20T11:57:16.743Z',
            assigned: true,
            position: 1,
            caption: null,
            url: 'https://rradar-accounts.imgix.net/uploads/32acb501-d2ce-45c5-b2ad-7d30cad6556b.jpeg?ixlib=rb-3.1.1',
          },
        ],
        visuals: [
          {
            id: 59,
            uuid: '32acb501-d2ce-45c5-b2ad-7d30cad6556b',
            file_type: 'jpeg',
            created_at: '2020-03-20T11:57:16.743Z',
            updated_at: '2020-03-20T11:57:16.743Z',
            assigned: true,
            position: 1,
            caption: null,
            url: 'https://rradar-accounts.imgix.net/uploads/32acb501-d2ce-45c5-b2ad-7d30cad6556b.jpeg?ixlib=rb-3.1.1',
          },
        ],
      },
      {
        id: 19,
        name: 'Calls',
        description: 'Call timer for JELF policy holders.',
        display_name: 'Calls (development)',
        application_url: 'https://calls.ui.2ra.co.uk',
        code_friendly_name: 'CALLS',
        app_store: {},
        marketing_url: null,
        light_logo_url: null,
        dark_logo_url: null,
        screenshots: [],
        visuals: [],
      },
      {
        id: 25,
        name: 'Edge',
        description: null,
        display_name: 'Edge',
        application_url: 'https://www.rradar.com/training',
        code_friendly_name: 'EDGE',
        app_store: {},
        marketing_url: null,
        light_logo_url: null,
        dark_logo_url: null,
        screenshots: [],
        visuals: [],
      },
      {
        id: 27,
        name: 'Test Scope Updates',
        description: null,
        display_name: 'Test Scope Updates',
        application_url: null,
        code_friendly_name: 'TEST_SCOPE_UPDATES',
        app_store: {},
        marketing_url: null,
        light_logo_url: null,
        dark_logo_url: null,
        screenshots: [
          {
            id: 40,
            uuid: '28839ed0-c9c0-4e8e-bd67-0471e60f89c6',
            file_type: 'jpeg',
            created_at: '2020-02-20T10:42:26.433Z',
            updated_at: '2020-02-20T10:42:26.433Z',
            assigned: true,
            position: 1,
            caption: null,
            url: 'https://rradar-accounts.imgix.net/uploads/28839ed0-c9c0-4e8e-bd67-0471e60f89c6.jpeg?ixlib=rb-3.1.1',
          },
        ],
        visuals: [
          {
            id: 40,
            uuid: '28839ed0-c9c0-4e8e-bd67-0471e60f89c6',
            file_type: 'jpeg',
            created_at: '2020-02-20T10:42:26.433Z',
            updated_at: '2020-02-20T10:42:26.433Z',
            assigned: true,
            position: 1,
            caption: null,
            url: 'https://rradar-accounts.imgix.net/uploads/28839ed0-c9c0-4e8e-bd67-0471e60f89c6.jpeg?ixlib=rb-3.1.1',
          },
        ],
      },
      {
        id: 30,
        name: 'Survey',
        description: null,
        display_name: 'Survey',
        application_url: null,
        code_friendly_name: 'SURVEY_DEV_SERVER',
        app_store: {},
        marketing_url: null,
        light_logo_url: null,
        dark_logo_url: null,
        screenshots: [],
        visuals: [],
      },
      {
        id: 38,
        name: 'RISK',
        description: 'Risk tool application',
        display_name: 'Risk',
        application_url: 'https://risk.ui.2ra.co.uk',
        code_friendly_name: 'RISK',
        app_store: {},
        marketing_url: null,
        light_logo_url:
          'https://rradar-accounts.imgix.net/uploads/faa8166d-f0fb-42af-b6ea-bb768823c50a.png?ixlib=rb-3.1.1',
        dark_logo_url:
          'https://rradar-accounts.imgix.net/uploads/02d73898-a768-4814-97df-0fc53b7ab5fd.png?ixlib=rb-3.1.1',
        screenshots: [],
        visuals: [],
      },
    ],
  },
  page: {
    id: NaN || null,
    parent: NaN || null,
  },
  api: {
    clientId: '',
    endpoint: 'https://station.api.2ra.co.uk',
    redirect_url_uid: '9915c1ab',
  },
};
window.__PUBLIC_STATE__Risk = {
  title: 'Risk Tool',
  user: {
    uid: '15316:36',
    user_id: 15316,
    company_id: 36,
    user_first_name: 'Rapha',
    user_last_name: 'Weedon',
    user_email: 'rapha.weedon@rradar.com',
    company_name: 'rradar',
    user_primary: true,
    scope: {
      features: [
        {
          WELCOME_TEXT: {
            value: ['hello'],
            amount: [],
            explicit: false,
            permission_type: 'feature',
            uuid: '6083318b-1dd8-4230-8ea9-07b6ad9f4854',
            name: 'Welcome Text',
            code_friendly_name: 'WELCOME_TEXT',
            uid: 'e3ab7da39959fe3af975227bca3173db',
          },
          GLOBAL_NEWS_AUTHOR: {
            value: [''],
            amount: [],
            explicit: true,
            permission_type: 'feature',
            uuid: '13492936-db6e-40fe-8191-cc27b44ad96d',
            name: 'Global News Author',
            code_friendly_name: 'GLOBAL_NEWS_AUTHOR',
            uid: 'cd5a25ec6984347c7f691ffafcf90957',
          },
          DOCUMENT_MANAGEMENT: {
            value: [],
            amount: ['200.0'],
            explicit: false,
            permission_type: 'feature',
            uuid: '33b5f868-1bd9-4fbd-9ca8-aaeb460e2939',
            name: 'Document Management',
            code_friendly_name: 'DOCUMENT_MANAGEMENT',
            uid: '900691e766b37fd4d70bcf166af87197',
          },
          RRADARRISK_ACCESS: {
            value: ['', 'TRUE'],
            amount: [],
            explicit: true,
            permission_type: 'feature',
            uuid: '967a8439-2c69-408f-9f06-beff021efff5',
            name: 'rradarrisk Access',
            code_friendly_name: 'RRADARRISK_ACCESS',
            uid: '0ff1e12c47fef60e0927cf9c84617d48',
          },
          SIDEKIQ: {
            value: [''],
            amount: [],
            explicit: false,
            permission_type: 'feature',
            uuid: 'c43df75d-fbe6-424e-88e9-c5771ab7984d',
            name: 'SideKiq',
            code_friendly_name: 'SIDEKIQ',
            uid: '35addcfcc779991ff0938d655b89be88',
          },
          RAT_MANAGEMENT: {
            value: [''],
            amount: [],
            explicit: false,
            permission_type: 'feature',
            uuid: '7b8bbc97-7aea-488c-9a19-40609909e472',
            name: 'RAT Management',
            code_friendly_name: 'RAT_MANAGEMENT',
            uid: '39a91e01753faaaa1f613067118c6690',
          },
        },
      ],
    },
    'risk_admin?': true,
    'risk_access?': true,
    me: {
      id: 15316,
      first_name: 'Rapha',
      last_name: 'Weedon',
      email: 'rapha.weedon@rradar.com',
      telephone: null,
      mobile: null,
      position: null,
      expires_at: null,
      locked: false,
      created_at: '2022-09-16T14:57:18.428Z',
      updated_at: '2025-02-18T13:08:09.478Z',
      expired: false,
      self_signup: false,
      verified: false,
      avatar_id: null,
      'complete?': true,
      avatar_url:
        'https://www.gravatar.com/avatar/744a859024066dc447b3510ca1fff96b?d=https://my.rradar.com/assets/img/default-profile.png',
      'blocked?': false,
    },
    company: {
      id: 36,
      name: 'rradar',
      logo_url:
        'https://rradar-accounts.imgix.net/uploads/5bd95208-bf10-47c5-a667-af354ea322f8.svg?ixlib=rb-3.1.1',
      sic_code_descriptions: [],
      can_switch: true,
      number_of_billable_users: 181,
    },
  },
  page: {
    id: NaN || null,
    parent: NaN || null,
  },
  api: {
    clientId: '63f19684-0349-4739-bce3-20d080b7e578',
    endpoint: 'https://dashboard.api.2ra.co.uk',
    redirect_url_uid: 'dc6ee4ae',
  },
};
